### ISSUE TITLE
Investigate using material typography for welcome page

### ISSUE THREAD

**Issue by jbergmark** [CodeForCary/cary-connects-web#37]
Based on my very naive understanding, the text recently added to the welcome page likely isn't following the larger material typography.

I suspect it could be re-worked using the documentation here:
https://material.io/design/typography/the-type-system.html#type-scale

while this certainly isn't my area of expertise by any means, I'm more than happy to give it a try.

**Comment by mccauleypeeler** [comment]
Yes you are correct if that’s something you want to work on then that’s awesome. Would be down to help

**Comment by jbergmark** [comment]
@mccauleypeeler I took an initial pass at converting over to using typography for the welcome screen.  UI design certainly isn't something I have much experience with, so I suspect there is a lot of room for improvement.

I've pushed that code to a branch named 'welcome-typography' if you wanted to try iterating on it.

**Comment by csellis** [comment]
I jumped in on this as well. It's looking good. I switched to MUI Link components so the links are a bit more visible.

**Comment by jbergmark** [comment]
@csellis Awesome, thank you!
